version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      aws lambda create-function \
      --function-name HelloWorldLambdaPipeline \
      --runtime python3.8 \
      --zip-file fileb://helloworld.zip \
      --handler helloworld.lambda_handler \
      --role arn:aws:iam::821383200340:role/AWS-Serverless-KatiMitja
